name: flutter_application_1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  kakao_flutter_sdk: ^1.9.0  # 카카오 로그인
  sign_in_with_apple: ^6.1.4  # 애플 로그인 (최신 버전)
  google_sign_in: ^6.2.1  # 구글 로그인 (최신 버전)
  dio: ^5.4.3+1  # HTTP 클라이언트
  flutter_riverpod: ^2.5.1  # 상태관리
  riverpod_annotation: ^2.3.5  # 리버팟 코드 생성 (버전 일치)
  flutter_secure_storage: ^9.0.0  # 보안 스토리지
  shared_preferences: ^2.2.3  # 로컬 스토리지
  json_annotation: ^4.9.0  # JSON 직렬화
  freezed_annotation: ^2.4.4  # freezed와 맞춤
  go_router: ^14.2.3  # 라우팅 (최신 안정 버전)
  ably_flutter: ^1.2.39  # Ably 실시간 메시징
  logger: ^2.0.2+1  # 로깅
  intl: ^0.19.0 # 날짜 및 시간 포맷팅
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.21.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0  # Dart 3.7.0 호환 안정 버전
  build_runner: ^2.4.11  # Dart 3.7.0 호환 안정 버전
  json_serializable: ^6.8.0  # Dart 3.7.0 호환 안정 버전
  freezed: ^2.5.2  # Dart 3.7.0 호환 안정 버전
  riverpod_generator: ^2.4.2  # Dart 3.7.0 호환 안정 버전

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env